import type { CollectionName } from "@/lib/types";

export type FieldType = "text" | "textarea" | "slug" | "url" | "date" | "boolean" | "array" | "imageArray" | "image" | "file" | "select" | "number";
export interface FieldConfig { key: string; label: string; type: FieldType; required?: boolean; options?: string[]; help?: string; }
export interface SectionConfig { collection: CollectionName; label: string; singular: string; titleKey: string; publicPath?: string; fields: FieldConfig[]; defaults: Record<string, unknown>; }

export const sections: Record<string, SectionConfig> = {
  projects: { collection: "projects", label: "Projects", singular: "project", titleKey: "name", publicPath: "/projects/", defaults: { name: "", slug: "", short_description: "", long_description: "", thumbnail_url: null, gallery_urls: [], technologies: [], github_url: null, live_url: null, demo_url: null, category: "", project_date: null, featured: false, status: "draft", sort_order: 0, metadata: {} }, fields: [
    { key: "name", label: "Name", type: "text", required: true }, { key: "slug", label: "Slug", type: "slug", required: true }, { key: "short_description", label: "Short description", type: "textarea", required: true }, { key: "long_description", label: "Full description (Markdown)", type: "textarea" }, { key: "thumbnail_url", label: "Thumbnail", type: "image" }, { key: "gallery_urls", label: "Project gallery", type: "imageArray" }, { key: "technologies", label: "Technologies", type: "array" }, { key: "category", label: "Category", type: "text" }, { key: "project_date", label: "Date", type: "date" }, { key: "github_url", label: "GitHub URL", type: "url" }, { key: "live_url", label: "Live URL", type: "url" }, { key: "demo_url", label: "Demo URL", type: "url" }, { key: "featured", label: "Featured", type: "boolean" }, { key: "status", label: "Visibility", type: "select", options: ["draft", "published", "hidden"] },
  ]},
  achievements: { collection: "achievements", label: "Achievements", singular: "achievement", titleKey: "title", publicPath: "/achievements#", defaults: { title: "", short_description: "", full_description: "", organization: null, achievement_date: null, category: "Award", image_url: null, external_url: null, featured: false, status: "draft", certificate_id: null, sort_order: 0 }, fields: [
    { key: "title", label: "Title", type: "text", required: true }, { key: "short_description", label: "Short description", type: "textarea", required: true }, { key: "full_description", label: "Full description", type: "textarea" }, { key: "organization", label: "Organization", type: "text" }, { key: "achievement_date", label: "Date", type: "date" }, { key: "category", label: "Category", type: "text" }, { key: "image_url", label: "Image", type: "image" }, { key: "external_url", label: "External URL", type: "url" }, { key: "certificate_id", label: "Certificate ID (from Certificates)", type: "text", help: "Leave empty to hide the certificate action publicly." }, { key: "featured", label: "Featured", type: "boolean" }, { key: "status", label: "Visibility", type: "select", options: ["draft", "published", "hidden"] },
  ]},
  certificates: { collection: "certificates", label: "Certificates", singular: "certificate", titleKey: "title", defaults: { title: "", file_url: "", file_type: "external", issuer: null, issued_at: null, sort_order: 0 }, fields: [
    { key: "title", label: "Title", type: "text", required: true }, { key: "file_url", label: "Certificate file or URL", type: "file", required: true }, { key: "file_type", label: "Type", type: "select", options: ["image", "pdf", "external"] }, { key: "issuer", label: "Issuer", type: "text" }, { key: "issued_at", label: "Issued date", type: "date" },
  ]},
  blog: { collection: "blog_posts", label: "Blog", singular: "post", titleKey: "title", publicPath: "/blog/", defaults: { title: "", slug: "", excerpt: "", content: "", cover_image_url: null, author: "M. Mahimmiraj", category: "Engineering", tags: [], published_at: null, featured: false, status: "draft", seo_title: null, seo_description: null, social_image_url: null, sort_order: 0 }, fields: [
    { key: "title", label: "Title", type: "text", required: true }, { key: "slug", label: "Slug", type: "slug", required: true }, { key: "content", label: "Content (Markdown)", type: "textarea", required: true }, { key: "cover_image_url", label: "Cover image", type: "image" }, { key: "author", label: "Author", type: "text" }, { key: "category", label: "Category", type: "text" }, { key: "tags", label: "Tags", type: "array" }, { key: "published_at", label: "Publication date", type: "date", help: "Leave blank to use the time you press Publish now." }, { key: "featured", label: "Featured", type: "boolean" }, { key: "status", label: "Publishing state", type: "select", options: ["draft", "published"], help: "Draft posts are private. Published posts appear on the public Blog page." }, { key: "seo_title", label: "SEO title", type: "text" }, { key: "seo_description", label: "SEO description", type: "textarea" }, { key: "social_image_url", label: "Social image", type: "image" },
  ]},
  gallery: { collection: "gallery_items", label: "Gallery", singular: "photo", titleKey: "alt_text", defaults: { title: null, caption: null, description: null, alt_text: "", category: null, image_url: "", thumbnail_url: "", featured: false, visible: true, sort_order: 0 }, fields: [
    { key: "image_url", label: "Photo", type: "image", required: true }, { key: "thumbnail_url", label: "Thumbnail URL", type: "url", help: "Defaults to the uploaded photo. Use an optimized thumbnail URL when available." }, { key: "title", label: "Title", type: "text" }, { key: "caption", label: "Caption", type: "text" }, { key: "description", label: "Description", type: "textarea" }, { key: "alt_text", label: "Alt text", type: "text", required: true }, { key: "category", label: "Category", type: "text" }, { key: "featured", label: "Featured", type: "boolean" }, { key: "visible", label: "Visible", type: "boolean" },
  ]},
  experience: { collection: "experiences", label: "Experience", singular: "experience", titleKey: "position", defaults: { position: "", company: "", description: "", start_date: null, end_date: null, current: false, technologies: [], external_url: null, sort_order: 0 }, fields: [
    { key: "position", label: "Position", type: "text", required: true }, { key: "company", label: "Company", type: "text", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "start_date", label: "Start date", type: "date" }, { key: "end_date", label: "End date", type: "date" }, { key: "current", label: "Current role", type: "boolean" }, { key: "technologies", label: "Technologies", type: "array" }, { key: "external_url", label: "External URL", type: "url" },
  ]},
  education: { collection: "education", label: "Education", singular: "education record", titleKey: "institution", defaults: { institution: "", degree: "", field: null, description: null, start_date: null, end_date: null, sort_order: 0 }, fields: [
    { key: "institution", label: "Institution", type: "text", required: true }, { key: "degree", label: "Degree", type: "text", required: true }, { key: "field", label: "Field", type: "text" }, { key: "description", label: "Description", type: "textarea" }, { key: "start_date", label: "Start date", type: "date" }, { key: "end_date", label: "End date", type: "date" },
  ]},
  skills: { collection: "skills", label: "Skills", singular: "skill", titleKey: "name", defaults: { name: "", category: "General", level: null, sort_order: 0 }, fields: [
    { key: "name", label: "Name", type: "text", required: true }, { key: "category", label: "Category", type: "text" }, { key: "level", label: "Level or note", type: "text" },
  ]},
};

export const sectionOrder = ["projects", "achievements", "certificates", "blog", "gallery", "experience", "education", "skills"];
