import { useEffect, useState, type FormEvent } from "react";
import { Loader2, Save } from "lucide-react";
import { getSettings, saveSettings } from "@/lib/contentRepository";
import { uploadMedia } from "@/lib/media";
import type { SiteSettings } from "@/lib/types";

export default function SettingsPage() {
  const [settings, setSettings] = useState<SiteSettings | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { void getSettings().then(setSettings); }, []);
  if (!settings) return <div className="admin-page text-zinc-500">Loading settings…</div>;
  const update = <K extends keyof SiteSettings>(key: K, value: SiteSettings[K]) => setSettings((current) => current ? { ...current, [key]: value } : current);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { setSettings(await saveSettings(settings)); setMessage("Settings saved successfully."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Save failed."); } finally { setSaving(false); } };
  const social = (key: string, value: string) => update("social_links", { ...settings.social_links, [key]: value });
  return <form onSubmit={submit} className="admin-page"><header className="mb-8"><h1 className="text-3xl font-semibold">Site Settings</h1><p className="mt-2 text-sm text-zinc-500">Global identity, contact and search information.</p></header><div className="space-y-6"><Field label="Name" value={settings.name} onChange={(value) => update("name", value)} required /><Field label="Short bio" value={settings.short_bio} onChange={(value) => update("short_bio", value)} textarea /><Field label="About" value={settings.about_content} onChange={(value) => update("about_content", value)} textarea /><div><span className="cms-label">Profile image</span>{settings.profile_image_url && <img src={settings.profile_image_url} alt="Profile preview" className="mb-3 h-24 w-24 rounded-full object-cover" />}<label className="action-secondary cursor-pointer">Choose photo<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={async (event) => { const file = event.target.files?.[0]; if (file) update("profile_image_url", await uploadMedia(file, "profile")); }} /></label></div><div className="grid gap-6 sm:grid-cols-2"><Field label="Email" type="email" value={settings.email} onChange={(value) => update("email", value)} required /><Field label="Phone" value={settings.phone || ""} onChange={(value) => update("phone", value)} /><Field label="Location" value={settings.location || ""} onChange={(value) => update("location", value)} /><Field label="GitHub" type="url" value={settings.social_links.github || ""} onChange={(value) => social("github", value)} /><Field label="LinkedIn" type="url" value={settings.social_links.linkedin || ""} onChange={(value) => social("linkedin", value)} /><Field label="Instagram" type="url" value={settings.social_links.instagram || ""} onChange={(value) => social("instagram", value)} /></div><div className="border-t border-zinc-800 pt-6"><h2 className="mb-5 text-lg font-semibold">SEO defaults</h2><div className="space-y-6"><Field label="SEO title" value={settings.seo_title} onChange={(value) => update("seo_title", value)} required /><Field label="SEO description" value={settings.seo_description} onChange={(value) => update("seo_description", value)} textarea required /><Field label="Footer text" value={settings.footer_text} onChange={(value) => update("footer_text", value)} /></div></div></div>{message && <p role="status" className="mt-6 text-sm text-zinc-300">{message}</p>}<div className="sticky bottom-[72px] mt-8 rounded-xl border border-zinc-700 bg-[#101014]/95 p-3 lg:bottom-4"><button disabled={saving} className="action-primary w-full justify-center py-3 sm:w-auto">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{saving ? "Saving…" : "Save settings"}</button></div></form>;
}

function Field({ label, value, onChange, textarea, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean; type?: string; required?: boolean }) {
  return <label className="block"><span className="cms-label">{label}</span>{textarea ? <textarea className="cms-input min-h-28" value={value} required={required} onChange={(event) => onChange(event.target.value)} /> : <input className="cms-input" type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} />}</label>;
}

